#!/usr/bin/env bash

set -euo pipefail

exit_code=0
while read suggestion; do
	if [[ ${suggestion} =~ ^(.*/)?internal/.*\.go: ]]; then
		# go files in internal packages
		if [[ ${suggestion} =~ exported\ .*\ should\ have\ comment\ or\ be\ unexported ]]; then
			# ignore suggestions
			continue
		fi
	fi
	echo "${suggestion}"
	exit_code=1
done
exit ${exit_code}
