name: ci
defaults:
  run:
    shell: bash
on:
  push:
    tags:
    - v*
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "image=ghcr.io/go-tk/ci:${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
    - run: docker build --tag='${{ env.image }}' . && docker push '${{ env.image }}'
