defaults:
  run:
    shell: bash
on:
  push:
    tags:
    - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: >-
        IMAGE=ghcr.io/go-tk/ci:${GITHUB_REF#refs/tags/} &&
        docker build --tag="${IMAGE}" . &&
        docker push "${IMAGE}"
